### ISSUE TITLE
Module view sometimes stop working

### ISSUE THREAD

**Issue by ghost** [ashbash1987/ktanemod-twitchplays#28]
Havn't found any way to reproduce it, but sometimes, the modules will not create view boxes anymore. Everything else works great while this is happening, but the modules will not display again until the next bomb.
Any way to fix this problem?

**Comment by ashbash1987** [comment]
Can't say I've been able to reproduce this effect. If you can get a VOD or video of it happening, that might help diagnose the issue you're having.

**Comment by bmn** [comment]
There used to be a bug where a camera slot would occasionally be "locked out" due to a race condition between
* the camera for a solved module being deactivated, and its slot set as not in use (after a short delay)
* any command moving a module on an existing camera to another camera

The new module would end up assigned to two active cameras, but since each camera looks at a different layer, only one would actually see the module - the other camera would appear to be inactive, but with no way of freeing it up short of assigning a higher-priority module to that slot (which isn't particularly likely with six slots).

I thought I'd fixed it, but it may just be that I made it less likely to occur.

In any case, there's some duplication of information (most importantly, the priority attribute) within ModuleCamera which is probably the root cause of most camera weirdness when they go out of sync. I was planning on limiting it to the ModuleItem only but never got round to it, will probably look at it sometime.

**Comment by bmn** [comment]
I've since seen this happen on a TP stream, it's not the situation I posted above. Camera behaviour is nonexistent for the entire bomb when this occurs, so likely an issue during bomb setup. Haven't been able to reproduce myself yet.

@arsenic87 If you see the issue occur again, it'd be helpful to close the game and upload ktane_Data/output_log.txt to a filesharing service for us to examine.
